title: Flock
tagline: Ride-sharing designed by college students, for college students.
email: flockunited1@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include: ['_pages', 'images']
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
- profiles
facebook: https://www.facebook.com/flockunited/
twitter: https://twitter.com/FlockUnited
prepend: https://128keaton.github.io/flockunited.com/images/
gh-pages: https://128keaton.github.io/flockunited.com/
instagram: https://www.instagram.com/flockunited/?hl=en

frontBlurb: Flock is a ride-sharing startup designed by college students, for college students. Our vision is to provide safe, cost-friendly ride-sharing with between students of the same university. After all, why ride with strangers when you have friends?
