title: Flock
tagline: Ride-sharing designed by college students, for college students.
email: flockunited1@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include: ['_pages', 'images']
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
- profiles
facebook: https://www.facebook.com/flockunited/
twitter: https://twitter.com/FlockUnited
